### ISSUE TITLE
EPIC: metadata for policies in artifacthub should be auto-generated

### ISSUE THREAD

**Issue by jordojordo** [kubewarden/ui#175]
Once the metadata in ArtifactHub contains the rules for each policy, the rule sets when creating a policy will need to be auto-generated, and possibly limit the ability to add more rules.

### Acceptace criteria

- [x] Artifacthub metadata API should expose policy's metadata.yml , and what one gets from a `kwctl scaffold`. Potentially: settings, rules, mutating, backgroundAudit.
  (e.g: [here](https://artifacthub.io/api/v1/packages/kubewarden/allowed-fsgroups-psp-policy/allowed-fsgroups-psp/0.1.4))
- [x] Create [questions.yaml](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#questionsyml) for policies.
  - Questions yaml can be found [here](https://github.com/kubewarden/ui/tree/main/pkg/kubewarden/questions/policy-questions)  
- [x] Ship questions.yaml for all policies. Either by embedding on metadata, or shipping charts owned by kubewarden.
- [ ] (see comments) Auto-generate artifacthub-pkg.yml from metadata.yml in all policy repos
- [x] Release new versions of policies
- [x] #211

**Comment by viccuad** [comment]
We have defined the usage of `artifacthub-pkg.yml` fields in UI, and how to derive them from `metadata.yml`.
We have hand-crafted `artifacthub-pkg.yml` for the policies to unblock the UI work.

Still, we are missing automating the generation of `artifacthub-pkg.yml`:
- [ ] https://github.com/kubewarden/kwctl/issues/418
- [ ] Document the usage of the new `kwctl scaffold artifacthub-pkg` for policy authors that want to publish in artifacthub.io
- [ ] Update GHA workflows to use the new kwctl command, and, either generate the new `artifacthub-pkg.yml`, or make sure it has automatically been updated and committed, prior to release
- [ ] Re-release policies
- [ ] Reach out to community policies and propose changes so they are published. See list in https://github.com/topics/kubewarden-policy (e.g: https://github.com/nlamirault/probes-policy, https://github.com/nlamirault/disallow-default-namespace-policy, ..)

**Comment by flavio** [comment]
Yes, that's totally correct. Can we turn https://github.com/kubewarden/ui/issues/175#issuecomment-1403373903 into a dedicated epic? This doesn't have anything to do with the UI right now

**Comment by viccuad** [comment]
Done, opened https://github.com/kubewarden/kubewarden-controller/issues/389.

Closing this as done.
