### ISSUE TITLE
UI v1

### ISSUE THREAD

**Issue by jordojordo** [kubewarden/ui#220]
Items left to tidy before publishing `v1`:

- [x] Remove line break from Default policies chart banner "Install Chart" button
- [x] Replace icons (signed, mutation) with text in policy cards listed on creation screen
- [x] Fix color of policy state in detail page
- [x] #219 
- [x] Change "Install Monitoring" link to a button in monitoring tab
- [x] Remove color from policy operation in traces
- [x] Make layout of tracing columns consistent with Policy list views
  - Change layout to: Mode, Name, Operation, Kind, Namespace, Start Time, Duration
- [x] Update and publish https://github.com/kubewarden/kubewarden.io/pull/150 & https://github.com/kubewarden/docs/pull/147
  - Update installation steps to remove the requirement of adding the UI Helm chart as a repository as [this repo](https://github.com/rancher/ui-plugin-charts) will contain the `v1` extension and will be automatically added to Rancher
    - [x] Update blog pr
    - [x] Update docs pr
- [x] Add `kubewarden/ui` repo to the `rancher/ui-plugin-charts` [manifest](https://github.com/rancher/ui-plugin-charts/blob/main/manifest.json)
- [x] Bump `./package.json` & `./pkg/kubewarden/package.json`  versions

**Comment by viccuad** [comment]
> Change layout to: Mode, Kind, Name, Operation, Namespace, Start Time, Duration

I would put "Operation, Kind, Namespace" columns closer to each other (e.g: "rejected in monitor mode a CREATE operation of Pod in Namespace default").

**Comment by jordojordo** [comment]
Perhaps the layout could be: "Mode, Name, Operation, Kind, Namespace, Start Time, Duration"?

**Comment by viccuad** [comment]
That layout order sounds good to me :).

**Comment by jordojordo** [comment]
1.0.0 has been released! Here are a few links to the [release](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.0), the [blog post](https://www.kubewarden.io/blog/2023/02/ui-1.0.0-release/) and the [documentation](https://docs.kubewarden.io/operator-manual/ui-extension/install).
