### ISSUE TITLE
Update policy questions

### ISSUE THREAD

**Issue by jordojordo** [kubewarden/ui#244]
Reliant on #243 for new SequenceMap questions component

Policies which contain settings that require a sequence of mappings need to provide a new questions type of `sequence[` with the following scaffold of [allowed-fsgroups-psp](https://github.com/kubewarden/allowed-fsgroups-psp-policy#settings) for example:

```yml
questions:
- default: [] # the default should be an empty array
  tooltip: Valid user ID (UID) ranges for the fsGroup.
  group: Settings
  label: User ID Ranges
  required: true
  type: sequence[ # this determines the question type
  variable: ranges
  sequence_questions: # this is required to show subsequent inputs
    - default: 1000
      tooltip: Minimum UID range for fsgroup.
      group: Settings
      label: min
      type: int
      variable: min # note the variable does not contain the parent property
    - default: 2000
      tooltip: Maximum UID range for fsgroup.
      group: Settings
      label: max
      type: int
      variable: max
```

### Policies update for `sequence[` type
- [x] ___allowed-fsgroups-psp___
  - PR:  https://github.com/kubewarden/allowed-fsgroups-psp-policy/pull/24
- [x] ___environment-variable-policy___
  - Related issue: #241 
  - PR: https://github.com/kubewarden/environment-variable-policy/pull/12
- [x] ___[verify-image-signatures](https://github.com/kubewarden/verify-image-signatures)___
  - Related issue: #239
  - PR: https://github.com/kubewarden/verify-image-signatures/pull/59
- [x] ___host-namespaces-psp___
  - Related issue: #238 
  - PR: https://github.com/kubewarden/host-namespaces-psp-policy/pull/18
- [x] ___[hostpaths-psp-policy](https://github.com/kubewarden/hostpaths-psp-policy)___
  - Related issue:  #236
  - PR: https://github.com/kubewarden/hostpaths-psp-policy/pull/12
- [x] ___selinux-psp-policy___
  - Related issue: #240
  - PR:  https://github.com/kubewarden/selinux-psp-policy/pull/38
- [x] ___user-group-psp-policy___
  - PR: https://github.com/kubewarden/user-group-psp-policy/pull/46

### Policies update other
- [x] ___[deprecated-api-versions-policy](https://github.com/kubewarden/deprecated-api-versions-policy)___ needs required prop
  - Related issue: #242
  - PR: https://github.com/kubewarden/deprecated-api-versions-policy/pull/17
- [x] ___[verify-image-signatures](https://github.com/kubewarden/verify-image-signatures#settings)___ needs options
  - Related issue #237 
  - PR: https://github.com/kubewarden/verify-image-signatures/pull/59
