### ISSUE TITLE
UI:    - Fix issues with policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/ui#358]
- [x] https://github.com/kubewarden/ui/issues/262
- [x] https://github.com/kubewarden/ui/issues/297
- [x] https://github.com/kubewarden/ui/issues/299
- [x] https://github.com/kubewarden/ui/issues/362

**Comment by jordojordo** [comment]
Removing https://github.com/kubewarden/ui/issues/257 from the list as this is [reliant](https://github.com/kubewarden/ui/issues/257#issuecomment-1572302609) on new policy releases. Closing as the rest of the tasks are completed
